name: medical_app
description: "A new Flutter project."
publish_to: 'none'
 
version: 1.0.0+1
 
environment:
  sdk: ^3.7.0
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_core: ^4.10.0
  file_picker: ^8.0.0        # lets user pick any file
  path_provider: ^2.1.0      # get app documents directory
  mime: ^1.0.4               # detect MIME type
  open_filex: ^4.3.4         # open file with device app
  path: ^1.9.1
  http: ^1.2.0               # GitHub REST API calls
  image_picker: ^1.1.2       # camera & gallery capture
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:
  assets:
    - assets/
  uses-material-design: true